services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env.production
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
