-- Migration: add BYOK customerKekWrapped field to Project
-- and BreakGlassToken table for emergency access (Addendum E.6)

ALTER TABLE "Project"
  ADD COLUMN IF NOT EXISTS "customerKekWrapped" TEXT;

-- Break-glass emergency access tokens.
-- Time-limited, single-use tokens generated by a super-admin for out-of-band
-- recovery when normal auth is unavailable.
CREATE TABLE IF NOT EXISTS "BreakGlassToken" (
  "id"           TEXT NOT NULL PRIMARY KEY,
  "tokenHash"    TEXT NOT NULL,
  "createdById"  TEXT NOT NULL,
  "reason"       TEXT,
  "expiresAt"    TIMESTAMP(3) NOT NULL,
  "usedAt"       TIMESTAMP(3),
  "usedByIp"     TEXT,
  "revoked"      BOOLEAN NOT NULL DEFAULT false,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "BreakGlassToken_expiresAt_idx" ON "BreakGlassToken"("expiresAt");
CREATE UNIQUE INDEX IF NOT EXISTS "BreakGlassToken_tokenHash_key" ON "BreakGlassToken"("tokenHash");
